-- Author: Nehal Parsekar
-- Roll No: 1942

CREATE TABLE Users(
	id VARCHAR(256) PRIMARY KEY,
	userName VARCHAR(32) NOT NULL,
	userAddress VARCHAR(128) NOT NULL,
	userYear INT NOT NULL,
	userGender VARCHAR(8) NOT NULL,
	userContact VARCHAR(16) NOT NULL,
	userEmail VARCHAR(256),
	userPassword VARCHAR(256),
	createdAt TIMESTAMP NOT NULL,
	updatedAt TIMESTAMP NOT NULL,
	userType VARCHAR(8) NOT NULL
);

CREATE TABLE States(
	id VARCHAR(256) PRIMARY KEY,
	stateName VARCHAR(32) NOT NULL,
	adminId VARCHAR(256) NOT NULL REFERENCES Users(id),
	status TINYINT NOT NULL,
	createdAt TIMESTAMP NOT NULL,
	updatedAt TIMESTAMP NOT NULL
);

CREATE TABLE Stations(
	id VARCHAR(256) PRIMARY KEY,
	stateId VARCHAR(256) NOT NULL REFERENCES States(id),
	adminId VARCHAR(256) NOT NULL REFERENCES Users(id),
	stationName VARCHAR(32) NOT NULL,
	status TINYINT NOT NULL,
	createdAt TIMESTAMP NOT NULL,
	updatedAt TIMESTAMP NOT NULL
);

CREATE TABLE Trains(
	id VARCHAR(256) PRIMARY KEY,
	trainName VARCHAR(32) NOT NULL,
	acSeats INTEGER NOT NULL,
	generalSeats INTEGER NOT NULL,
	adminId VARCHAR(256) NOT NULL REFERENCES Users(id),
	status TINYINT NOT NULL,
	createdAt TIMESTAMP NOT NULL,
	updatedAt TIMESTAMP NOT NULL
);

CREATE TABLE Schedules(
	id VARCHAR(256) PRIMARY KEY,
	scheduleName VARCHAR(32) NOT NULL,
	adminId VARCHAR(256) NOT NULL REFERENCES Users(id),
	arrival TIME NOT NULL,
	departure TIME NOT NULL,
	status TINYINT NOT NULL,
	createdAt TIMESTAMP NOT NULL,
	updatedAt TIMESTAMP NOT NULL
);

CREATE TABLE Routes(
	id VARCHAR(256) PRIMARY KEY,
	routeName VARCHAR(64) NOT NULL,
	routeFare FLOAT NOT NULL,
	adminId VARCHAR(256) NOT NULL REFERENCES Users(id),
	sStationId VARCHAR(256) NOT NULL REFERENCES Stations(id),
	dStationId VARCHAR(256) NOT NULL REFERENCES Stations(id),
	status TINYINT NOT NULL,
	createdAt TIMESTAMP NOT NULL,
	updatedAt TIMESTAMP NOT NULL
);

CREATE TABLE RouteSchedules(
	id VARCHAR(256) PRIMARY KEY,
	routeId VARCHAR(256) NOT NULL REFERENCES Routes(id),
	scheduleId VARCHAR(256) NOT NULL REFERENCES Schedules(id),
	createdAt TIMESTAMP NOT NULL,
	updatedAt TIMESTAMP NOT NULL
);

CREATE TABLE RouteTrains(
	id VARCHAR(256) PRIMARY KEY,
	routeId VARCHAR(256) NOT NULL REFERENCES Routes(id),
	trainId VARCHAR(256) NOT NULL REFERENCES Trains(id),
	createdAt TIMESTAMP NOT NULL,
	updatedAt TIMESTAMP NOT NULL
);

CREATE TABLE Members(
	id VARCHAR(256) PRIMARY KEY,
	adminId VARCHAR(256) NOT NULL REFERENCES Users(id),
	userId VARCHAR(256) NOT NULL REFERENCES Users(id),
	createdAt TIMESTAMP NOT NULL,
	updatedAt TIMESTAMP NOT NULL
);

CREATE TABLE Bookings(
	id VARCHAR(256) PRIMARY KEY,
	bookingDate DATE NOT NULL,
	routeId VARCHAR(256) NOT NULL REFERENCES Routes(id),
	scheduleId VARCHAR(256) NOT NULL REFERENCES Schedules(id),
	trainId VARCHAR(256) NOT NULL REFERENCES Trains(id),
	aGeneralSeats INT NOT NULL,
	aAcSeats INT NOT NULL,
	bGeneralSeats INT NOT NULL,
	bAcSeats INT NOT NULL,
	createdAt TIMESTAMP NOT NULL,
	updatedAt TIMESTAMP NOT NULL
);

CREATE TABLE Tickets(
	id VARCHAR(256) PRIMARY KEY,
	userId VARCHAR(256) NOT NULL REFERENCES Users(id),
	adminId VARCHAR(256) NOT NULL REFERENCES Users(id),
	trainId VARCHAR(256) NOT NULL REFERENCES Trains(id),
	routeId VARCHAR(256) NOT NULL REFERENCES Routes(id),
	scheduleId VARCHAR(256) NOT NULL REFERENCES Schedule(id),
	sStateId VARCHAR(256) NOT NULL REFERENCES States(id),
	dStateId VARCHAR(256) NOT NULL REFERENCES States(id),
	sStationId VARCHAR(256) NOT NULL REFERENCES Stations(id),
	dStationId VARCHAR(256) NOT NULL REFERENCES Stations(id),
	ticketDate DATE NOT NULL,
	ticketCoach TINYINT NOT NULL,
	status TINYINT NOT NULL,
	ticketFare FLOAT NOT NULL,
	createdAt TIMESTAMP NOT NULL,
	updatedAt TIMESTAMP NOT NULL
);











